from src.pages.algorithm_lab.pymoo.problems.single.ackley import *
from src.pages.algorithm_lab.pymoo.problems.single.cantilevered_beam import *
from src.pages.algorithm_lab.pymoo.problems.single.griewank import *
from src.pages.algorithm_lab.pymoo.problems.single.knapsack import *
from src.pages.algorithm_lab.pymoo.problems.single.pressure_vessel import *
from src.pages.algorithm_lab.pymoo.problems.single.rastrigin import *
from src.pages.algorithm_lab.pymoo.problems.single.rosenbrock import *
from src.pages.algorithm_lab.pymoo.problems.single.schwefel import *
from src.pages.algorithm_lab.pymoo.problems.single.sphere import *
from src.pages.algorithm_lab.pymoo.problems.single.zakharov import *
from src.pages.algorithm_lab.pymoo.problems.single.g import *
from src.pages.algorithm_lab.pymoo.problems.single.himmelblau import *