from src.pages.algorithm_lab.pymoo.problems.multi.bnh import *
from src.pages.algorithm_lab.pymoo.problems.multi.carside import *
from src.pages.algorithm_lab.pymoo.problems.multi.ctp import *
from src.pages.algorithm_lab.pymoo.problems.multi.dascmop import *
from src.pages.algorithm_lab.pymoo.problems.multi.kursawe import *
from src.pages.algorithm_lab.pymoo.problems.multi.modact import *
from src.pages.algorithm_lab.pymoo.problems.multi.mw import *
from src.pages.algorithm_lab.pymoo.problems.multi.osy import *
from src.pages.algorithm_lab.pymoo.problems.multi.srn import *
from src.pages.algorithm_lab.pymoo.problems.multi.tnk import *
from src.pages.algorithm_lab.pymoo.problems.multi.truss2d import *
from src.pages.algorithm_lab.pymoo.problems.multi.welded_beam import *
from src.pages.algorithm_lab.pymoo.problems.multi.zdt import *
