FIELD_LABEL: dict[str, str] = {
    "university": "院校",
    "major": "专业",
    "major_2": "第二专业",
    "gpa": "GPA",
    "gpa_scale": "GPA制",
    "language_type": "语言",
    "language_score": "语言成绩",
    "standardized_test_type": "标化",
    "standardized_test_score": "标化成绩",
    "country": "目标地区",
    "target_schools": "目标院校",
    "target_majors": "目标专业",
    "research": "科研",
    "research_details": "科研项目",
    "internship": "实习",
    "internship_details": "实习经历",
    "paper": "论文",
    "paper_details": "论文发表",
    "award": "奖项",
    "award_details": "获奖情况",
}
